[FIX] Network Explorer: Clear selection on new network and when removing network
biolab/orange3-network pull request #184
Opened 2021-01-29 14:43 UTC by janezd

##### Issue

Fixes #111.

##### Includes
- [X] Code changes
- [X] Tests

2021-02-09 06:19 UTC, VesnaT commented
The `Network Explorer` widget does not work for me. 
There seems to be a problem with `_fr_layout`

2021-02-11 14:49 UTC, janezd commented
I just tried with a fresh environment. In it
- I installed orange3 from conda-forge
- install cython
- ran `python setup.py develop` in orange, base widget and canvas
- ran `pip install -e .` in network add (I don't know why I used pip here... out of habit?)
... and everything works.

I don't know how to replicate and debug this. And I don't know what could be wrong, actually.

BTW, how does it doesn't work?

2021-02-12 10:19 UTC, VesnaT requested changes
I guess, the cleared selection should result on the `selected_data` output as well, but it does not:
Connect Network File -> Network Explorer -> Data Table (with Selected Data) and select some points. After removing the Network File, selected data retains in Data Table. The same selected data is there after re-connecting Network File to Network Explorer with some other network.

This seems strange, since sending the `selected data` should be handled in parent widget.

2021-02-12 10:21 UTC, VesnaT commented on orangecontrib/network/widgets/tests/test_OWNxExplorer.py
> +        self.assertIsNone(self.widget.selection)
I prefer testing a widgets behavior to its properties. This test does not assure no selection on the output.
Adding

`self.assertIsNone(self.get_output(self.widget.Outputs.selected_data))`

results in failed test.

2021-02-25 12:40 UTC, janezd commented
> This seems strange, since sending the selected data should be handled in parent widget.

`handleNewSignals` does not call the inherited method because the derived widget is too different. (We have had similar problems in other widgets, too.)

The overriden version did not call `unconditional_commit`.

2021-02-26 12:55 UTC, VesnaT commented
When opening a saved workflow with selected instances, the selection is cleared. Is that intentional?

2021-02-27 19:00 UTC, janezd commented
Here's another one: select some variable for Color. Then remove data. Variable remains selected.

I discovered this when fixing the pending selection. This widget does not properly reset itself because it does not call the inherited methods for this. The reason is, as I recall, that it's signals are a bit more complicated. @VesnaT, when we can work together again, we should study this problem together.

2026-05-19 09:27 UTC, merged